# Generated by Django 4.1.4 on 2022-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_alter_main_anime_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_anime',
        ),
        migrations.DeleteModel(
            name='PresetList',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('x', 'filled'), ('y', 'notfilled')], default='', max_length=60, verbose_name='gender'),
        ),
    ]
