# Generated by Django 4.1.4 on 2022-12-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_main_anime_delete_presetlist_delete_search_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
