# Generated by Django 4.1.4 on 2022-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='bin_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('status', models.CharField(blank=True, choices=[('y', 'filled'), ('n', 'notfilled')], default='', max_length=60, verbose_name='status')),
            ],
        ),
    ]
