# Generated by Django 4.1.4 on 2022-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bin_status_lat_alter_bin_status_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin_status',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bin_status',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
