# Generated by Django 4.1.4 on 2022-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_bin_status_lat_alter_bin_status_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location1_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location1image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('location2_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location2_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location2image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('location3_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location3_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location3image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('location4_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location4_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location4image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
    ]
