# Generated by Django 4.1.4 on 2022-12-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_camera_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location1_lat',
            new_name='loc1_lat',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location1_lng',
            new_name='loc1_lng',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location1image',
            new_name='loc1image',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location2_lat',
            new_name='loc2_lat',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location2_lng',
            new_name='loc2_lng',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location2image',
            new_name='loc2image',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location3_lat',
            new_name='loc3_lat',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location3_lng',
            new_name='loc3_lng',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location3image',
            new_name='loc3image',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location4_lat',
            new_name='loc4_lat',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location4_lng',
            new_name='loc4_lng',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='location4image',
            new_name='loc4image',
        ),
    ]
