# Generated by Django 4.1.4 on 2022-12-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_camera_vision_loc1status_camera_vision_loc2status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera_vision',
            old_name='loc1_lat',
            new_name='loc_lat',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='loc1_lng',
            new_name='loc_lng',
        ),
        migrations.RenameField(
            model_name='camera_vision',
            old_name='loc1image',
            new_name='locimage',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc1status',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc2_lat',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc2_lng',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc2image',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc2status',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc3_lat',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc3_lng',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc3image',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc3status',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc4_lat',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc4_lng',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc4image',
        ),
        migrations.RemoveField(
            model_name='camera_vision',
            name='loc4status',
        ),
    ]
