# Generated by Django 4.1.4 on 2023-01-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_bin_status_lat_alter_bin_status_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='arduino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, default=0, null=True, verbose_name='distance')),
                ('check_filled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bin_status', verbose_name='check_filled')),
            ],
        ),
    ]
