# Generated by Django 4.1.4 on 2023-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_arduino'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='fill_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
