# Generated by Django 4.1.4 on 2023-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_u_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u_details',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='u_details',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='u_details',
            name='area_assigned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='u_details',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='u_details',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='u_details',
            name='status',
            field=models.CharField(blank=True, choices=[('y', 'filled'), ('n', 'notfilled')], default='', max_length=60, verbose_name='status'),
        ),
    ]
