# Generated by Django 4.1.4 on 2023-02-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_name_u_details_user_name_u_details_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_details',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('driver', 'driver')], default='', max_length=60, verbose_name='status'),
        ),
    ]
